create extension if not exists pgcrypto;

create table if not exists public.stores (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  website_url text,
  affiliate_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint stores_slug_format check (
    slug = lower(slug)
    and slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'
  )
);

create table if not exists public.promo_codes (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete cascade,
  code text not null,
  title text,
  description text,
  destination_url text not null,
  expires_at timestamptz,
  approved boolean not null default false,
  is_active boolean not null default true,
  click_count bigint not null default 0 check (click_count >= 0),
  worked_count integer not null default 0 check (worked_count >= 0),
  failed_count integer not null default 0 check (failed_count >= 0),
  submitted_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (store_id, code)
);

create table if not exists public.promo_votes (
  id uuid primary key default gen_random_uuid(),
  promo_id uuid not null references public.promo_codes(id) on delete cascade,
  vote_type text not null check (vote_type in ('worked', 'failed')),
  fingerprint text not null check (
    char_length(fingerprint) between 8 and 200
  ),
  created_at timestamptz not null default now(),
  unique (promo_id, fingerprint)
);

create table if not exists public.promo_clicks (
  id bigint generated by default as identity primary key,
  promo_id uuid not null references public.promo_codes(id) on delete cascade,
  fingerprint text,
  created_at timestamptz not null default now()
);

create index if not exists promo_codes_public_lookup_idx
  on public.promo_codes (store_id, approved, is_active, expires_at);

create index if not exists promo_codes_created_at_idx
  on public.promo_codes (created_at desc);

create index if not exists promo_votes_promo_id_idx
  on public.promo_votes (promo_id);

create index if not exists promo_clicks_promo_id_created_at_idx
  on public.promo_clicks (promo_id, created_at desc);
